# Generated by Django 3.2.3 on 2021-05-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventia_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='event_registration',
        ),
    ]
