# Generated by Django 3.2.3 on 2021-05-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventia_web', '0002_rename_destination_event_registration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event_registration',
            new_name='event_registrations',
        ),
    ]
