# Generated by Django 3.2.3 on 2021-05-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventia_web', '0003_rename_event_registration_event_registrations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event_registrations',
        ),
    ]
